### ISSUE TITLE
下载成功未转为mp4格式

### ISSUE THREAD

**Issue by ZhangWei12138** [lytian/m3u8_downloader#9]
只有ts文件的文件夹 连m3u8的文件都没有, 下载成功之后`filePath`也是返回`null`
我下载的是加密的视频文件，不知道是不是这个原因导致的

**Comment by lytian** [comment]
超过1G的视频文件处理可能会失败，这个原因也在排查

**Comment by ZhangWei12138** [comment]
> 超过1G的视频文件处理可能会失败，这个原因也在排查

没有超过1G，两百多兆的视频

**Comment by ZhangWei12138** [comment]
@lytian  终于找到原因了，是key文件加载的内容错了，我看到你的代码里是这样写的，是否是因为未判断key文件的地址导致key文件地址错误，这里直接用了url的地址+key文件名，但是我的key文件是一个单独的文件与url域名不一样。不知道我理解的是否正确，希望作者能解答一下，感谢。
https://github.com/lytian/m3u8_downloader/blob/995902669d3f8614a8bb0ac032bfdc44b41b407e/android/src/main/java/vincent/m3u8_downloader/utils/MUtils.java#L37-L86

**Comment by ZhangWei12138** [comment]
https://github.com/lytian/m3u8_downloader/blob/995902669d3f8614a8bb0ac032bfdc44b41b407e/android/src/main/java/vincent/m3u8_downloader/utils/MUtils.java#L66
我把这句改成这样，key文件正常下载了
``` java
String keyUrl = v.startsWith("http") ? v : (basePath + v);
```
但是出现了新问题，key文件我直接下载下来是16个字节的，但是通过代码下载下来的变成了34个字节，就报错了
```log
W/System.err(15247): java.security.InvalidKeyException: Unsupported key size: 34 bytes
W/System.err(15247): 	at com.android.org.conscrypt.OpenSSLCipher$EVP_CIPHER$AES.checkSupportedKeySize(OpenSSLCipher.java:802)
W/System.err(15247): 	at com.android.org.conscrypt.OpenSSLCipher.checkAndSetEncodedKey(OpenSSLCipher.java:471)
W/System.err(15247): 	at com.android.org.conscrypt.OpenSSLCipher.engineInit(OpenSSLCipher.java:298)
W/System.err(15247): 	at javax.crypto.Cipher.tryTransformWithProvider(Cipher.java:2980)
W/System.err(15247): 	at javax.crypto.Cipher.tryCombinations(Cipher.java:2891)
W/System.err(15247): 	at javax.crypto.Cipher$SpiAndProviderUpdater.updateAndGetSpiAndProvider(Cipher.java:2796)
W/System.err(15247): 	at javax.crypto.Cipher.chooseProvider(Cipher.java:773)
W/System.err(15247): 	at vincent.m3u8_downloader.utils.AES128Utils.decryptTs(AES128Utils.java:144)
W/System.err(15247): 	at vincent.m3u8_downloader.M3U8DownloadTask.convertMP4(M3U8DownloadTask.java:410)
W/System.err(15247): 	at vincent.m3u8_downloader.M3U8DownloadTask.access$1100(M3U8DownloadTask.java:39)
W/System.err(15247): 	at vincent.m3u8_downloader.M3U8DownloadTask$2$1.run(M3U8DownloadTask.java:199)
E/M3U8Log (15247): onError: Unsupported key size: 34 bytes

```

**Comment by lytian** [comment]
加密算法不一致的问题，你需要对key解密的地方处理一下

**Comment by ZhangWei12138** [comment]
编码改为 ISO-8859-1 之后解决了
